### ISSUE TITLE
A question about NMSE

### ISSUE THREAD

**Issue by SwiftBrown** [abdulkarimgizzini/Low-Complex-Methods-for-Robust-Channel-Estimation-in-Doubly-Dispersive-Environments#1]
Hello! I am very interested in this paper recently and I have a question and would like to ask for your help. As mentioned in the paper, the error only occurs when estimating(HLS_P), but when I use the real channel response matrix h, it still has NMSE error. I don't understand the reason for this. This is the image I ran with matlab2021b where the black line used real channel response.  I think NMSE and BER should be 0 in this case. Would you mind helping me? Thank you very much.

![image](https://github.com/abdulkarimgizzini/Low-Complex-Methods-for-Robust-Channel-Estimation-in-Doubly-Dispersive-Environments/assets/136573074/8d04d6ec-9581-41fb-8078-ebcb8cf76107)
![image](https://github.com/abdulkarimgizzini/Low-Complex-Methods-for-Robust-Channel-Estimation-in-Doubly-Dispersive-Environments/assets/136573074/c3e90d5a-0db7-436d-97f3-50140a0b6481)

**Comment by abdulkarimgizzini** [comment]
Hello,
Thank you for your interest in my research. Actually, I didn't get your
point. Could you please elaborate more on the problem? Please note that we
can schedule an online meeting to discuss further if needed.
--
Best regards,
Abdul Karim GIZZINI
_____________________________________________________
Postdoctoral Researcher
IMT Nord Europe, Institut Mines-Télécom, University of Lille.
Rue Guglielmo Marconi, 59650 Villeneuve-d'Ascq.

**Comment by SwiftBrown** [comment]
Thank you for your response,There is indeed a problem with my way of asking questions and I have got that by reading your literature carefully . I need to learn more about your papers in the future.Thank you.
